docs: Article about contrast
digdir/designsystemet pull request #1362
Opened 2024-01-10 10:27 UTC by mrosvik

@Camulos will add content.

2024-04-11 06:51 UTC, Ildest commented on apps/storefront/pages/god-praksis/index.mdx
> +    title='Ny kontrastmetode utforskes'
Forslag til overskrift: WCAG 3.0 foreslår ny kontrastmetode

2024-04-11 06:52 UTC, Ildest commented on apps/storefront/pages/god-praksis/tilgjengelighet/kontrast.mdx
> +  description='Våre retningslinjer for kontrast'
WCAG 3.0 foreslår ny kontrastmetode

2024-04-11 06:52 UTC, Ildest commented on apps/storefront/pages/god-praksis/tilgjengelighet/kontrast.mdx
> +      title: 'Ny kontrastmetode utforskes',
WCAG 3.0 foreslår ny kontrastmetode

2024-04-11 06:54 UTC, Ildest commented on apps/storefront/pages/god-praksis/tilgjengelighet/kontrast.mdx
> +For å sikre god lesbarhet skal all tekst ha tilstrekkelig kontrast mot bakgrunnen. Dette er viktig for alle brukere, særlig under krevende lysforhold. De som trenger dette mest, er svaksynte, dyslekt
Tegnsetting: Liten K og punktum til etter UU-tilsynet.

De som trenger dette mest, er svaksynte, dyslektikere og fargeblinde (kilde: [uutilsynet](https://www.uutilsynet.no/veiledning/kontrast/48)).

2024-04-11 06:56 UTC, Ildest commented on apps/storefront/pages/god-praksis/tilgjengelighet/kontrast.mdx
> +## Ny metode utforskes
WCAG 3.0 foreslår en mer presis metode

2024-04-11 06:59 UTC, Ildest commented on apps/storefront/pages/god-praksis/tilgjengelighet/kontrast.mdx
> +En ny metode som er mer presis enn dagens standard for å kalkulere kontrast og sette terskelverdier, utforskes nå i WCAG 3.0.
Prøv å ikke ha verbet og hva/hvem som gjør noe så langt bak i setningen (her er det utforskes), det blir tungt: 

WCAG 3.0 utforsker nå en mer presis metode enn dagens standard, for å kalkulere kontrast og sette terskelverdier.

2024-04-11 07:03 UTC, Ildest commented on apps/storefront/pages/god-praksis/tilgjengelighet/kontrast.mdx
> +      Metoden forbedrer hvordan verdien mellom to farger bestemmes, og gjør også
Metoden forbedrer hvordan verdien mellom to farger bestemmes, og skiller også på om fargene er i forgrunnen eller i bakgrunnen.

2024-04-11 07:05 UTC, Ildest commented on apps/storefront/pages/god-praksis/tilgjengelighet/kontrast.mdx
> +## Vi bruker i dag en ønsket standard
I dag bruker vi en høyere standard enn kravene til tilgjengelighet

2024-04-11 07:07 UTC, Ildest commented on apps/storefront/pages/god-praksis/tilgjengelighet/kontrast.mdx
> +For at innholdet i offentlige, digitale tjenester skal være tilgjengelig for brukerne, også de med svekket syn, bruker vi i dag en ønsket standard for kontrast, som er høyere enn kravene som stilles
For at innholdet i offentlige, digitale tjenester skal være tilgjengelig for alle brukere, følger vi i dag en ønsket standard for kontrast som er høyere enn kravene som stilles til tilgjengelighet. Standarden heter WCAG 2.1,  nivå AAA.
For å øke lesbarheten enda mer, har vi ambisjoner om å oppnå kontrast på nivå 4. Det er toppnivået i APCA-metoden, som nå blir foreslått i WCAG 3.0

2024-04-11 07:07 UTC, Ildest commented on apps/storefront/pages/god-praksis/tilgjengelighet/kontrast.mdx
> +For å øke lesbarheten ytterligere, er ambisjonen vår å oppnå kontrast på nivå 4, som er toppnivået i APCA-metoden, som nå blir utforsket i WCAG 3.0.
For å øke lesbarheten enda mer, har vi ambisjoner om å oppnå kontrast på nivå 4. Det er toppnivået i APCA-metoden, som nå blir foreslått i WCAG 3.0

2024-04-11 07:10 UTC, Ildest commented on apps/storefront/pages/god-praksis/tilgjengelighet/kontrast.mdx
> +Metoden er ikke vitenskapelig støttet, hvis vi måler opp mot lesbarhet og tilgjengelighet. Det betyr at løsningen ikke er universelt utformet. Siden øyets evne til å oppfatte farger og lys ikke er en
Mener vi her at den ikke er brukertestet tilstrekkelig før den ble foreslått? I så fall er det mer presist å si enn "ikke vitenskapelig støttet". 

Forslag: "Metoden er ikke godt nok brukertestet når det gjelder lesbarhet og tilgjengelighet enda.

2024-04-11 07:10 UTC, Ildest commented on apps/storefront/pages/god-praksis/tilgjengelighet/kontrast.mdx
> +Hvis vi oppfyller metoden i WCAG 2, etterlever vi teknisk sett kravet til Universell utforming, men det betyr ikke at innholdet er tilgjengelig eller universelt utformet. Derfor strekker vi oss langt
Liten u i universell her

2024-04-11 07:14 UTC, Ildest requested changes
@mrosvik da har jeg vært gjennom denne

2024-04-11 07:41 UTC, mrosvik commented on apps/storefront/pages/god-praksis/tilgjengelighet/kontrast.mdx
> +## Ny metode utforskes
Hvor?

2024-04-11 07:44 UTC, Ildest commented on apps/storefront/pages/god-praksis/tilgjengelighet/kontrast.mdx
> +  description='Våre retningslinjer for kontrast'
@mrosvik Her ser jeg ikke i den publiserte artikkelen at det står noen tittel som heter bare "Kontrast", så jeg vet ikke helt hvordan koden er bygd opp her.

2024-04-11 07:45 UTC, Ildest commented on apps/storefront/pages/god-praksis/tilgjengelighet/kontrast.mdx
> +  description='Våre retningslinjer for kontrast'
Ser ut som dette er bare metadata - du kan sikkert ignorer denne rettingen

2024-04-11 07:45 UTC, mrosvik commented on apps/storefront/pages/god-praksis/tilgjengelighet/kontrast.mdx
> +## Vi bruker i dag en ønsket standard
Hvor?

2024-04-11 07:50 UTC, mrosvik commented on apps/storefront/pages/god-praksis/tilgjengelighet/kontrast.mdx
> +Metoden er ikke vitenskapelig støttet, hvis vi måler opp mot lesbarhet og tilgjengelighet. Det betyr at løsningen ikke er universelt utformet. Siden øyets evne til å oppfatte farger og lys ikke er en
Forslag fra Roy: Vi vet at selv om en løsning oppfyller de konkrete kravene fra regelverket om universell utforming, så er den ikke nødvendigvis universelt utformet og tilgjengelig

2024-04-11 07:51 UTC, mrosvik commented on apps/storefront/pages/god-praksis/tilgjengelighet/kontrast.mdx
> +Metoden er ikke vitenskapelig støttet, hvis vi måler opp mot lesbarhet og tilgjengelighet. Det betyr at løsningen ikke er universelt utformet. Siden øyets evne til å oppfatte farger og lys ikke er en
Vi vet at selv om en løsning oppfyller de konkrete kravene fra regelverket om universell utforming, så er den ikke nødvendigvis universelt utformet og tilgjengelig. Siden øyets evne til å oppfatte farger og lys ikke er en del av metoden, er den uegnet til å beregne forskjellen i lysstyrken i fargeparet.

2024-04-11 08:24 UTC, Ildest commented on apps/storefront/pages/god-praksis/tilgjengelighet/kontrast.mdx
> +## Vi bruker i dag en ønsket standard
Som overskrift

2024-04-11 08:28 UTC, Ildest commented on apps/storefront/pages/god-praksis/tilgjengelighet/kontrast.mdx
> +## Ny metode utforskes
Koblet til overskriften i linje 96

2024-04-11 08:29 UTC, Ildest commented on apps/storefront/pages/god-praksis/tilgjengelighet/kontrast.mdx
> +      Målet vårt er å ligge over AAA-krav i WCAG 2.1, og vi vil dermed ligge
Det øker sjansen for at vi klarer å...

2024-04-11 09:23 UTC, mrosvik commented on apps/storefront/pages/god-praksis/tilgjengelighet/kontrast.mdx
> +## Ny metode utforskes
Blir den for lik hovedoverskriften?

2024-04-11 10:48 UTC, mrosvik reviewed
Endinger er lagt inn

2024-04-11 11:24 UTC, Ildest approved these changes

2024-04-11 17:22 UTC, mrosvik commented
Need approval from @Barsnes or @mimarz.

2024-04-12 06:06 UTC, Barsnes approved these changes

2024-04-12 06:07 UTC, merged