Fix: Update nested list spacing
digdir/designsystemet pull request #1365
Opened 2024-01-11 03:33 UTC by ramanand-rv

This PR aims to fix #1359 

### Changes Made:

Adjusted styles for the nested List and List Item components.
Set margin-top for the nested List Item to var(--fds-spacing-2).

Please review the changes in the styles for the nested List and List Item components. Ensure that the spacing adjustments align with the design requirements. The goal is to enhance the visual presentation and maintain a clear hierarchy within the nested list structure. In case of further changes please notify me, I would love to contribute here.

Thank you for your review!

2024-01-11 08:04 UTC, mimarz requested changes
Hi @ramanand-rv!

Thanks for wanting to contribute to our project! I left you a review on respective changes in code as a separate comment.

In addition:
- Make sure to have the correct line ending (LF) for the file. You can see Github giving a warning in the "files changed" tab.
- We use [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/) and use scope for the affected components, which means the PR title should start with "fix(List):" instead of just "fix:"

2024-01-11 08:11 UTC, mrosvik commented
@ramanand-rv Thank you for contributing ❤️ And I apologize for my poor explanation. I meant to say that the _Nested_ list was missing spacing-2 above it, where the red arrow is. 😊

2024-01-12 14:55 UTC, ramanand-rv commented on packages/react/src/components/List/List.module.css
> +}
Thanks @mimarz for the helpful review comment. Will implement the changes and update the PR accordingly.

2024-01-17 13:35 UTC, Barsnes commented
Hi @ramanand-rv, do you have a time estimate of when you would be able to get this done?

2024-01-19 08:10 UTC, Barsnes commented
Closing this issue as we waited a week with no changes made.
This will be resolved in #1402

2024-01-19 08:10 UTC, closed without merging