feat(List): Add support for custom heading id
digdir/designsystemet pull request #1394
Opened 2024-01-17 11:09 UTC by Barsnes

Adds support for passing a custom heading id

2024-01-17 18:23 UTC, mimarz requested changes
We can add this for now, but maybe refactor this so you can use it with your own `Heading`. Exposing tunnel props doesn't exactly scale well. 

If we move the `...rest` further down (keeping `style` & `className`) to the ul/li element. People can then combine their own `Heading` and `List` with `aria-labelledby`

2024-01-17 18:23 UTC, mimarz commented on packages/react/src/components/List/List.tsx
> +          id={headingId ?? hId}
Suggest making a separate `const` for the since its used multiple places.

2024-01-17 18:24 UTC, mimarz approved these changes
Forgot to change submit type 🦭

2024-01-18 07:37 UTC, Barsnes commented
> We can add this for now, but maybe refactor this so you can use it with your own `Heading`. Exposing tunnel props doesn't exactly scale well.
> 
> If we move the `...rest` further down (keeping `style` & `className`) to the ul/li element. People can then combine their own `Heading` and `List` with `aria-labelledby`

Yes I agree, we should not have a heading prop. I proposed this when making the list, but we decided not do it, since it would have to be client rendered for the `aria-labelled` by to work.

2024-01-18 07:51 UTC, merged

2024-01-18 11:12 UTC, Barsnes commented
> We can add this for now, but maybe refactor this so you can use it with your own `Heading`. Exposing tunnel props doesn't exactly scale well.
> 
> If we move the `...rest` further down (keeping `style` & `className`) to the ul/li element. People can then combine their own `Heading` and `List` with `aria-labelledby`

I have made a PR with a potential change to how we use the `List`: #1400
Read the description for more thoughts