refactor(accordion): Start BEM migration
digdir/designsystemet pull request #1870
Opened 2024-04-23 12:41 UTC by poi33

New accodion.css with BEM naming
Refactored from Accordion.module.css

2024-04-23 14:17 UTC, poi33 commented
Do we want the `open` modifier to be part of the `.accordion` block: `.accordion--open` 
Or closer to its implementation of `.accordion__item`  element: `.accordion__item--open` ?

2024-04-24 12:45 UTC, mimarz requested changes
Awesome work!

I like that you took the time to clean up the css as well. Some components CSS are better than other, so its also something we do whenever we see the need 🙌

Two things I forgot to mention in the "main" issue:
- Prefix the new classes with `fds-`
- Make sure to run `build` in the root (or `packages/react`) to generate a new `react-css-modules.css` which excludes the now removed css modules css :) 

(I've also updated the main issue with these points)

2024-04-24 12:45 UTC, mimarz commented on packages/react/src/components/Accordion/AccordionHeader/AccordionHeader.tsx
> +          className={cl('accordion__expand-icon')}
Suggest removing redundant use of `clsx` if its not needed :)
```suggestion
          className='accordion__expand-icon'
```

2024-04-25 20:03 UTC, mimarz approved these changes
LGTM 👍 

Thank you!

2024-04-26 05:41 UTC, merged