docs: sizing guidelines for Button
digdir/designsystemet pull request #2013
Opened 2024-05-16 06:49 UTC by mrosvik

2024-05-16 11:30 UTC, mimarz approved these changes

2024-05-16 11:33 UTC, Barsnes requested changes

2024-05-16 11:33 UTC, Barsnes commented on packages/react/src/components/Button/Button.mdx
> -
We decided not to remove this story yet, but add text saying we will remove it later on

2024-05-22 11:46 UTC, Barsnes requested changes

2024-05-22 11:46 UTC, Barsnes commented on packages/react/src/components/Button/Button.stories.tsx
> -
This needs to be added back for the story to work

2024-05-22 11:53 UTC, Barsnes approved these changes

2024-05-23 09:37 UTC, merged