feat(switch): Accessibility update
digdir/designsystemet pull request #2073
Opened 2024-05-24 16:18 UTC by poi33

Fix for #2057

Tested with NVDA for readout for screen readers. 

Before code changes: "clickable  (label text) check box  not checked"

After code changes: "clickable (label text) switch  off"

For a standard switch this would be an improvement. (Not part of a form submission. A toggle switch on a website)

For the design system usecase: "A choice between two options" and being a part of forms I think the checkbox better conveys how to use it to screen readers.

2024-05-30 07:58 UTC, Barsnes requested changes
Reading https://www.w3.org/WAI/ARIA/apg/patterns/switch/examples/switch-checkbox/, I think we should do this.
But it also says that
> If the switch element is an HTML input[type="checkbox"], it uses the HTML checked attribute instead of the aria-checked property.

so I think we should remove this, and only have `role="switch"`

2024-05-30 11:04 UTC, poi33 commented
@Barsnes what about the `role="switch"` having a confusing readout for a form submission input? If its part of a form I would suggest to not use the changes.

2024-05-30 17:19 UTC, mimarz commented
> @Barsnes what about the `role="switch"` having a confusing readout for a form submission input? If its part of a form I would suggest to not use the changes.

hmm, I haven't had a chance to test this, but our guidelines you should use `Checkbox` for forms and `Switch` for more "settings" and simple toggle actions in a UI. 

I see [react-aria](https://react-spectrum.adobe.com/react-aria/Switch.html) also use this role, so I suggest lets go for it!

2024-06-03 06:25 UTC, mimarz approved these changes

2024-06-03 06:29 UTC, mimarz commented on packages/react/src/components/form/Switch/Switch.tsx
> +            aria-checked={inputProps.checked}
This is redundant as its already an input with `type="checkbox"`
```suggestion
```

2024-06-03 13:28 UTC, poi33 commented
Closing this, as the switch will need a bigger refactor if we don't want to use it for form submissions.

2024-06-03 13:28 UTC, closed without merging