Article about error messages (Cross-agency cooperation)
digdir/designsystemet pull request #2096
Opened 2024-06-04 07:10 UTC by mrosvik

2024-08-05 11:12 UTC, Barsnes requested changes
Har retta på litt skrivefeil, men ser også at lister variera på om dei begynner med stor eller liten bokstav. Er dette bestemt med om lista ligger bak kolon, eller ikkje?

2024-08-05 11:12 UTC, Barsnes commented on apps/storefront/pages/monstre/feilmeldinger.mdx
> +#### Slik plasser vi en feilmelding
```suggestion
#### Slik plasserer vi en feilmelding
```

2024-08-05 11:12 UTC, Barsnes commented on apps/storefront/pages/monstre/feilmeldinger.mdx
> +  Merk: Vi ønsker å holde oss oppdatert om andre anbefalinger om plasseringen, og har [pågående diskusjon om dette på Git](https://github.com/digdir/designsystemet/discussions/1684#discussioncomment-
```suggestion
  Merk: Vi ønsker å holde oss oppdatert om andre anbefalinger om plassering, og har [pågående diskusjon om dette på Git](https://github.com/digdir/designsystemet/discussions/1684#discussioncomment-9339006).
```

2024-08-05 11:12 UTC, Barsnes commented on apps/storefront/pages/monstre/feilmeldinger.mdx
> +Vi kan vise feilmeldinger når brukerne forlater feltet eller når de velger å gå videre eller sende inn. Vi unngår å vise feilmeldinger mens brukeren fyller ut et felt.
```suggestion
Vi kan vise feilmeldinger når brukerne forlater feltet, når de velger å gå videre, eller sender inn. Vi unngår å vise feilmeldinger mens brukeren fyller ut et felt.
```

2024-08-05 11:12 UTC, Barsnes commented on apps/storefront/pages/monstre/feilmeldinger.mdx
> +Hadde det bare vært en feil i gruppen, ville feilmeldingen vist på vanlig måte under kun et av feltene, uten at hele gruppen ble rød.
```suggestion
Hadde det vært bare en feil i gruppen, ville feilmeldingen vist på vanlig måte under kun et av feltene, uten at hele gruppen ble rød.
```

2024-08-05 11:12 UTC, Barsnes commented on apps/storefront/pages/monstre/feilmeldinger.mdx
> +Vi bruker ikke deaktivert Gå videre/Send inn-knapp til å validere skjema. Noen brukere forstår ikke hvorfor knappen er deaktivert og blir forvirret. Brukere med nedsatt syn kan slite med å finne knap
```suggestion
Vi bruker ikke deaktivert "Gå videre/Send inn"-knapp til å validere skjema. Noen brukere forstår ikke hvorfor knappen er deaktivert og blir forvirret. Brukere med nedsatt syn kan slite med å finne knappen og tro at skjemaet har tekniske problemer. Hvis brukerne prøver å gå videre mens det fortsatt er feil i skjemaet, kan vi heller vise en oppsummerende feilmelding over "Gå videre/Send inn"-knappen.
```

2024-08-05 11:12 UTC, Barsnes commented on apps/storefront/pages/monstre/feilmeldinger.mdx
> +  Vi unngår inntill videre å bruke `aria-errormessage` da den ikke har full støtte av hjelpemidler per nå. Men vi kommer til å oppdatere retningslinjene om støtten blir bedre i fremtiden. [diskusjon
```suggestion
  Vi unngår inntill videre å bruke `aria-errormessage` da den ikke har full støtte av hjelpemidler per nå. Men vi kommer til å oppdatere retningslinjene om støtten blir bedre i fremtiden. [Se diskusjon på github](https://github.com/digdir/designsystemet/discussions/1684)
```

2024-08-05 11:12 UTC, Barsnes commented on apps/storefront/pages/monstre/feilmeldinger.mdx
> +Vi kan også gi automatiske beskjeder når vi vil at brukeren så snart som mulig skal få opplest viktig informasjon. Det kan for eksempel være når det blir en stor visuell endring eller nytt innhold.
```suggestion
Vi kan også gi automatiske beskjeder når vi vil at brukeren så snart som mulig skal få opplest viktig informasjon. Det kan for eksempel være når det blir en stor visuell endring, eller nytt innhold.
```

2024-08-06 05:52 UTC, mrosvik commented
> Har retta på litt skrivefeil, men ser også at lister variera på om dei begynner med stor eller liten bokstav. Er dette bestemt med om lista ligger bak kolon, eller ikkje?

Bra funn @Barsnes ! ⭐️ Ja, det er noen regler, @Ildest har skrevet om det i liste-komponenten. 

Når hvert punkt er en fortsettelse av innledningen til punktlisten, som er mest vanlig, bruker vi
·      liten forbokstav i punktene
·      ikke kolon etter innledningen
·      ikke punktum eller komma til slutt på hvert punkt  

Når punktene er hele setninger, bruker vi stor forbokstav i det første ordet og punktum til slutt på hvert punkt.

2024-08-06 06:21 UTC, Barsnes approved these changes
🚀

2024-08-06 06:54 UTC, merged