Docs/chip guidelines
digdir/designsystemet pull request #2218
Opened 2024-08-08 12:34 UTC by mrosvik

2024-08-09 06:18 UTC, Barsnes requested changes

2024-08-09 06:18 UTC, Barsnes commented on packages/react/src/components/Chip/Chip.mdx
>  i Chip ikke forklarer at den kan fjernes. I dette eksempelet er det lagt til `aria-label="Slett nynorsk"`.
Dette stemmer ikkje heilt overens med storyen som er lagt til. Burde oppdatere teksten, eller endre på story

2024-08-09 06:18 UTC, Barsnes commented on packages/react/src/components/Chip/Chip.mdx
> +- Ikke bruk `Chip` som varsler for antall nye elementer eller status. Bruk heller [`Badge`](/docs/komponenter-badge--docs)-komponenten.
```suggestion
- Ikke bruk `Chip` som varsler for antall eller status. Bruk heller [`Badge`](/docs/komponenter-badge--docs)-komponenten.
```
Det er ikkje kun nye element, men antall generelt.

2024-08-09 06:18 UTC, Barsnes commented on packages/react/src/components/Chip/Chip.mdx
> +- varsler for antall nye elementer eller status (bruk heller [`Badge`](/docs/komponenter-badge--docs))
```suggestion
- varsler for antall eller status (bruk heller [`Badge`](/docs/komponenter-badge--docs))
```
Det er ikkje kun nye element, men antall generelt.

2024-08-12 07:46 UTC, mrosvik commented on packages/react/src/components/Chip/Chip.mdx
>  i Chip ikke forklarer at den kan fjernes. I dette eksempelet er det lagt til `aria-label="Slett nynorsk"`.
Funker det bedre nå?

2024-08-12 07:48 UTC, Barsnes commented on packages/react/src/components/Chip/Chip.mdx
> +i Chip ikke forklarer at den kan fjernes. I dette eksempelet er det lagt til `aria-label="Slett Danmark"`.
```suggestion
i Chip ikke forklarer at den kan fjernes. I dette eksempelet er det lagt til `aria-label="Slett {land}"`.
```

2024-08-12 12:08 UTC, merged