feat: input with select and textbox
digdir/designsystemet pull request #2571
Opened 2024-10-04 08:03 UTC by eirikbacker

- Adds `select` and `textarea` to #2550

2024-10-08 10:13 UTC, eirikbacker commented on packages/css/input.css
> +      resize: none;
La være på?

2024-10-11 10:08 UTC, mimarz requested changes
Suggest adding a changeset detailing actual changes here since we have users using & testing `@next`. There are quite a few breaking changes here. 

Are we moving completely away from `label` props now and favouring composition with `Label` and `Field.*`?

2024-10-11 10:11 UTC, eirikbacker commented
Yes, completely moving towards Field-API, and leaving native elements as pure as possible avoiding anyt confusion on what is a `<select>` vs. `<Select>` 🙌

2024-10-11 10:29 UTC, mimarz commented
> Yes, completely moving towards Field-API, and leaving native elements as pure as possible avoiding anyt confusion on what is a `<select>` vs. `<Select>` 🙌

Sounds good, we just have to make sure we document it for people testing and using `@next`. I assume we will batch these changes into the same release anyways.

2024-10-11 10:29 UTC, mimarz approved these changes
Here goes nothing! 🎸

2024-10-11 10:42 UTC, merged