chore: new neutral color logic
digdir/designsystemet pull request #2911
Opened 2024-12-17 07:56 UTC by Thunear

2025-01-28 07:23 UTC, Barsnes commented on apps/theme/app/themebuilder/_components/ThemePages.module.css
>    background-color: var(--ds-color-neutral-background-subtle);
```suggestion
  background-color: var(--ds-color-neutral-background-tinted);
```
This does not change color, but it probably should. It's the one in the back
![image](https://github.com/user-attachments/assets/8b443157-802a-439b-89d2-0e914f7aeb9c)

2025-01-28 07:32 UTC, Barsnes commented on apps/theme/app/themebuilder/_components/ThemePages.module.css
>    background-color: var(--ds-color-neutral-background-subtle);
The same also applies to the preview on the frontpage
![image](https://github.com/user-attachments/assets/c8ac016b-cdb2-49c4-a479-3334d13d63b4)

2025-01-28 10:22 UTC, mimarz commented
merge this after #3006

2025-01-28 11:56 UTC, mimarz requested changes
I will do some changes here in regard to color structure and generation to improve concurrency across the Designsystem

2025-01-31 08:38 UTC, Barsnes approved these changes

2025-01-31 11:27 UTC, mimarz approved these changes

2025-01-31 11:28 UTC, merged